> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 456-115-780
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 127.0.0.1 - - [25/Feb/2019 15:34:30] "GET /admin/ HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:34:35] "GET /admin/user/ HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:34:46] "GET /admin/user/new/?url=%2Fadmin%2Fuser%2F HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:40:39] "GET /admin/user/new/?url=%2Fadmin%2Fuser%2F HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:41:02] "POST /admin/user/new/sample HTTP/1.1" 404 -
> 127.0.0.1 - - [25/Feb/2019 15:41:20] "POST /admin/user/new/sample HTTP/1.1" 404 -
> 127.0.0.1 - - [25/Feb/2019 15:41:31] "POST /admin/user/new/sample HTTP/1.1" 404 -
> 127.0.0.1 - - [25/Feb/2019 15:41:50] "GET /admin/ HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:41:54] "GET /admin/user/new/?url=%2Fadmin%2Fuser%2F HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:42:27] "POST /admin/user/new/?url=%2Fadmin%2Fuser%2F HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_admin\base.py", line 69, in inner
>     return self._run_view(f, *args, **kwargs)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_admin\base.py", line 368, in _run_view
>     return fn(self, *args, **kwargs)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_admin\model\base.py", line 2048, in create_view
>     model = self.create_model(form)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_admin\contrib\sqla\view.py", line 1085, in create_model
>     if not self.handle_view_exception(ex):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_admin\contrib\sqla\view.py", line 1068, in handle_view_exception
>     return super(ModelView, self).handle_view_exception(exc)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_admin\contrib\sqla\view.py", line 1082, in create_model
>     self._on_model_change(form, model, True)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_admin\model\base.py", line 1548, in _on_model_change
>     self.on_model_change(form, model, is_created)
> TypeError: on_model_change() takes exactly 3 arguments (4 given)
> 127.0.0.1 - - [25/Feb/2019 15:42:28] "GET /admin/user/new/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:42:28] "GET /admin/user/new/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:42:29] "GET /admin/user/new/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:42:29] "GET /admin/user/new/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:42:29] "GET /admin/user/new/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:42:29] "GET /admin/user/new/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
>  * To enable the debugger you need to enter the security pin:
>  * Debugger pin code: 456-115-780
> 127.0.0.1 - - [25/Feb/2019 15:42:47] "GET /admin/user/new/?__debugger__=yes&cmd=printpin&s=t7HcoOH0jZDhjahMTAGS HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:43:11] "GET /admin/user/new/?__debugger__=yes&cmd=pinauth&pin=456-115-780&s=t7HcoOH0jZDhjahMTAGS HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:43:19] "GET /admin/user/new/?url=%2Fadmin%2Fuser%2F&__debugger__=yes&cmd=self&frm=107720152&s=t7HcoOH0jZDhjahMTAGS HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:43:27] "GET /admin/user/new/?url=%2Fadmin%2Fuser%2F&__debugger__=yes&cmd=self.on_model_change&frm=107720152&s=t7HcoOH0jZDhjahMTAGS HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:43:31] "GET /admin/user/new/?url=%2Fadmin%2Fuser%2F&__debugger__=yes&cmd=form&frm=107720152&s=t7HcoOH0jZDhjahMTAGS HTTP/1.1" 200 -
> 127.0.0.1 - - [25/Feb/2019 15:43:37] "GET /admin/user/new/?url=%2Fadmin%2Fuser%2F&__debugger__=yes&cmd=help(form)&frm=107720152&s=t7HcoOH0jZDhjahMTAGS HTTP/1.1" 200 -
>  * Detected change in 'C:\\Users\\gherz-PC\\Desktop\\remidiv2\\serveus\\models.py', reloading
