> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 456-115-780
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 127.0.0.1 - - [17/Mar/2019 20:30:39] "GET /case/6/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:30:40] "GET /static/favicon.ico HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:30:44] "GET /records/1 HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:30:48] "GET /case/7/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:30:49] "GET /pic/29/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:30:50] "GET /case/5/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:30:51] "GET /pic/27/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:30:51] "GET /pic/26/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:30:59] "GET /pic/29/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:33:09] "GET /case/7/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 694, in case
>     return render_template("case.html", MLDiagnosis = MLDiagnosis, MLScore = MLScore, MLDetections = MLDetections, MLSpecies = MLSpecies, case = case, user = current_user, images=images, disease_list=disease_list, specimen_types=specimen_types, hide_microscopist=app.config['HIDE_MICROSCOPIST_FROM_VALIDATOR'])
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 134, in render_template
>     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
>     return self.get_template(template_name_or_list, parent, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 830, in get_template
>     return self._load_template(name, self.make_globals(globals))
> 127.0.0.1 - - [17/Mar/2019 20:33:09] "GET /case/7/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 804, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\loaders.py", line 125, in load
>     code = environment.compile(source, name, filename)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 591, in compile
>     self.handle_exception(exc_info, source_hint=source_hint)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\case.html", line 99, in template
>     <img src="/MLPic/{{i.split('/')[1]}}" alt="" id="case_img_/{{i}}" onclick="img_click(this.id, '{{\'/MLPic/\'+i.split(\'/\')[1]}}')">
> TemplateSyntaxError: unexpected char u'\\' at 7976
> 127.0.0.1 - - [17/Mar/2019 20:33:10] "GET /case/7/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:33:10] "GET /case/7/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:33:10] "GET /case/7/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:33:10] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:33:10] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:33:44] "GET /case/7/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
> 127.0.0.1 - - [17/Mar/2019 20:33:44] "GET /case/7/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
>     response = self.full_dispatch_request()
> 127.0.0.1 - - [17/Mar/2019 20:33:44] "GET /case/7/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 694, in case
>     return render_template("case.html", MLDiagnosis = MLDiagnosis, MLScore = MLScore, MLDetections = MLDetections, MLSpecies = MLSpecies, case = case, user = current_user, images=images, disease_list=disease_list, specimen_types=specimen_types, hide_microscopist=app.config['HIDE_MICROSCOPIST_FROM_VALIDATOR'])
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 134, in render_template
>     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
>     return self.get_template(template_name_or_list, parent, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 830, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 804, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\loaders.py", line 125, in load
>     code = environment.compile(source, name, filename)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 591, in compile
>     self.handle_exception(exc_info, source_hint=source_hint)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\case.html", line 99, in template
>     <img src="/MLPic/{{i.split('/')[1]}}" alt="" id="case_img_/{{i}}" onclick="img_click(this.id, '{{\'/MLPic/\'+i.split(\'/\')[1]}}')">
> TemplateSyntaxError: unexpected char u'\\' at 7976
> 127.0.0.1 - - [17/Mar/2019 20:33:44] "GET /case/7/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:33:44] "GET /case/7/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:33:44] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:33:45] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:34:53] "GET /case/7/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
> 127.0.0.1 - - [17/Mar/2019 20:34:53] "GET /case/7/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 694, in case
>     return render_template("case.html", MLDiagnosis = MLDiagnosis, MLScore = MLScore, MLDetections = MLDetections, MLSpecies = MLSpecies, case = case, user = current_user, images=images, disease_list=disease_list, specimen_types=specimen_types, hide_microscopist=app.config['HIDE_MICROSCOPIST_FROM_VALIDATOR'])
> 127.0.0.1 - - [17/Mar/2019 20:34:53] "GET /case/7/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 134, in render_template
>     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
>     return self.get_template(template_name_or_list, parent, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 830, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 804, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\loaders.py", line 125, in load
>     code = environment.compile(source, name, filename)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 591, in compile
>     self.handle_exception(exc_info, source_hint=source_hint)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\case.html", line 99, in template
>     <img src="\MLPic\{{i.split('\')[1]}}" alt="" id="case_img_/{{i}}" onclick="img_click(this.id, '{{\'/MLPic/\'+i.split(\'/\')[1]}}')">
> TemplateSyntaxError: expected token ',', got '{'
> 127.0.0.1 - - [17/Mar/2019 20:34:53] "GET /case/7/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:34:54] "GET /case/7/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:34:54] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:34:54] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:35:25] "GET /case/7/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
> 127.0.0.1 - - [17/Mar/2019 20:35:25] "GET /case/7/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:35:25] "GET /case/7/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 694, in case
>     return render_template("case.html", MLDiagnosis = MLDiagnosis, MLScore = MLScore, MLDetections = MLDetections, MLSpecies = MLSpecies, case = case, user = current_user, images=images, disease_list=disease_list, specimen_types=specimen_types, hide_microscopist=app.config['HIDE_MICROSCOPIST_FROM_VALIDATOR'])
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 134, in render_template
>     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
>     return self.get_template(template_name_or_list, parent, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 830, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 804, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\loaders.py", line 125, in load
>     code = environment.compile(source, name, filename)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 591, in compile
>     self.handle_exception(exc_info, source_hint=source_hint)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\case.html", line 99, in template
>     <img src="/MLPic/{{i[2:]}}" alt="" id="case_img_/{{i}}" onclick="img_click(this.id, '{{\'/MLPic/\'+i.split(\'/\')[1]}}')">
> TemplateSyntaxError: unexpected char u'\\' at 7966
> 127.0.0.1 - - [17/Mar/2019 20:35:25] "GET /case/7/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:35:25] "GET /case/7/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:35:26] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:35:26] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:05] "GET /case/7/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
> 127.0.0.1 - - [17/Mar/2019 20:36:05] "GET /case/7/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:05] "GET /case/7/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 694, in case
>     return render_template("case.html", MLDiagnosis = MLDiagnosis, MLScore = MLScore, MLDetections = MLDetections, MLSpecies = MLSpecies, case = case, user = current_user, images=images, disease_list=disease_list, specimen_types=specimen_types, hide_microscopist=app.config['HIDE_MICROSCOPIST_FROM_VALIDATOR'])
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 134, in render_template
>     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
>     return self.get_template(template_name_or_list, parent, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 830, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 804, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\loaders.py", line 125, in load
>     code = environment.compile(source, name, filename)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 591, in compile
>     self.handle_exception(exc_info, source_hint=source_hint)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\case.html", line 99, in template
>     <img src="/MLPic/{{i[2:]}}" alt="" id="case_img_/{{i}}" onclick="img_click(this.id, '{{\'/MLPic/\'+i[2:]}}')">
> TemplateSyntaxError: unexpected char u'\\' at 7966
> 127.0.0.1 - - [17/Mar/2019 20:36:06] "GET /case/7/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:06] "GET /case/7/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:06] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:06] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:11] "GET /case/7/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
> 127.0.0.1 - - [17/Mar/2019 20:36:11] "GET /case/7/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 694, in case
>     return render_template("case.html", MLDiagnosis = MLDiagnosis, MLScore = MLScore, MLDetections = MLDetections, MLSpecies = MLSpecies, case = case, user = current_user, images=images, disease_list=disease_list, specimen_types=specimen_types, hide_microscopist=app.config['HIDE_MICROSCOPIST_FROM_VALIDATOR'])
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 134, in render_template
>     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
>     return self.get_template(template_name_or_list, parent, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 830, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 804, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\loaders.py", line 125, in load
>     code = environment.compile(source, name, filename)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 591, in compile
>     self.handle_exception(exc_info, source_hint=source_hint)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\case.html", line 99, in template
>     <img src="/MLPic/{{i[2:]}}" alt="" id="case_img_/{{i}}" onclick="img_click(this.id, '{{\'/MLPic/\'+i[2:]}}')">
> TemplateSyntaxError: unexpected char u'\\' at 7966
> 127.0.0.1 - - [17/Mar/2019 20:36:11] "GET /case/7/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:11] "GET /case/7/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:11] "GET /case/7/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:11] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:12] "GET /case/7/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:47] "GET /case/7/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:36:47] "GET /MLPic/c/29 HTTP/1.1" 404 -
> 127.0.0.1 - - [17/Mar/2019 20:36:48] "GET /static/favicon.ico HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:37:12] "GET /MLpic/27/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:37:13] "GET /case/7/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:37:13] "GET /MLpic/c/29 HTTP/1.1" 404 -
> 127.0.0.1 - - [17/Mar/2019 20:37:14] "GET /static/favicon.ico HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:37:16] "GET /case/5/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:37:16] "GET /MLpic/c/26 HTTP/1.1" 404 -
> 127.0.0.1 - - [17/Mar/2019 20:37:17] "GET /MLpic/c/27 HTTP/1.1" 404 -
> 127.0.0.1 - - [17/Mar/2019 20:37:17] "GET /static/favicon.ico HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:08] "GET /case/5/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
> 127.0.0.1 - - [17/Mar/2019 20:39:08] "GET /case/5/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:08] "GET /case/5/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 694, in case
>     return render_template("case.html", MLDiagnosis = MLDiagnosis, MLScore = MLScore, MLDetections = MLDetections, MLSpecies = MLSpecies, case = case, user = current_user, images=images, disease_list=disease_list, specimen_types=specimen_types, hide_microscopist=app.config['HIDE_MICROSCOPIST_FROM_VALIDATOR'])
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 134, in render_template
>     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
>     return self.get_template(template_name_or_list, parent, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 830, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 804, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\loaders.py", line 125, in load
>     code = environment.compile(source, name, filename)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 591, in compile
>     self.handle_exception(exc_info, source_hint=source_hint)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\case.html", line 99, in template
>     <img src="/MLpic/{{i[len('pic/'):]}}" alt="" id="case_img_/{{i}}" onclick="img_click(this.id, '/MLpic/{{i[len(\'pic/\'):]}}')">
> TemplateSyntaxError: unexpected char u'\\' at 7989
> 127.0.0.1 - - [17/Mar/2019 20:39:08] "GET /case/5/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:08] "GET /case/5/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:09] "GET /case/5/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:09] "GET /case/5/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:29] "GET /case/5/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
> 127.0.0.1 - - [17/Mar/2019 20:39:29] "GET /case/5/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:29] "GET /case/5/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 694, in case
>     return render_template("case.html", MLDiagnosis = MLDiagnosis, MLScore = MLScore, MLDetections = MLDetections, MLSpecies = MLSpecies, case = case, user = current_user, images=images, disease_list=disease_list, specimen_types=specimen_types, hide_microscopist=app.config['HIDE_MICROSCOPIST_FROM_VALIDATOR'])
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 135, in render_template
>     context, ctx.app)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 117, in _render
>     rv = template.render(context)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\case.html", line 1, in top-level template code
>     {% extends "layout.html" %}
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\layout.html", line 184, in top-level template code
>     {% block content %}
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\case.html", line 99, in block "content"
>     <img src="/MLpic/{{i[len('pic/'):]}}" alt="" id="case_img_/{{i}}" onclick="img_click(this.id, '/MLpic/{{i[4:]}}')">
> UndefinedError: 'len' is undefined
> 127.0.0.1 - - [17/Mar/2019 20:39:30] "GET /case/5/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:30] "GET /case/5/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:30] "GET /case/5/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:30] "GET /case/5/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:43] "GET /case/5/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:43] "GET /MLpic/26 HTTP/1.1" 301 -
> 127.0.0.1 - - [17/Mar/2019 20:39:43] "GET /MLpic/27 HTTP/1.1" 301 -
> 127.0.0.1 - - [17/Mar/2019 20:39:45] "GET /MLpic/26/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:45] "GET /MLpic/27/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:39:46] "GET /static/favicon.ico HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:40:09] "GET /case/5/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:40:10] "GET /MLpic/26/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:40:11] "GET /MLpic/27/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:40:12] "GET /static/favicon.ico HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:40:14] "GET /MLpic/26/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:40:29] "GET /MLpic/27/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:41:47] "GET /MLpic/27/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:42:20] "GET /MLpic/27/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:42:36] "GET /records/1 HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:43:02] "GET /case/7/ HTTP/1.1" 200 -
> 127.0.0.1 - - [17/Mar/2019 20:43:04] "GET /MLpic/29/ HTTP/1.1" 200 -
