> Initialized logger
> Traceback (most recent call last):
>   File "run.py", line 13, in <module>
> app.run('0.0.0.0', port=80, debug = True, threaded = True)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 943, in run
> run_simple(host, port, self, **options)
>   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 795, in run_simple
> s.bind(get_sockaddr(hostname, port, address_family))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
> return getattr(self._sock,name)(*args)
> socket
> .
> error
> :
> [Errno 98] Address already in use
