> Initialized logger
> Traceback (most recent call last):
>   File "run.py", line 3, in <module>
> from serveus import app
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\__init__.py", line 92, in <module>
> detector()
> TypeError
> :
> 'module' object is not callable
